# Generated by Django 5.1.3 on 2025-02-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('planned', 'планируемая'), ('assigned', 'выполняется'), ('review', 'проверяется'), ('done', 'готова'), ('overdue', 'просрочена')], default='new', max_length=100),
        ),
    ]
