# Generated by Django 5.1.3 on 2025-02-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('planned', 'планируемая'), ('assigned', 'выполняется'), ('review', 'проверяется'), ('done', 'готова'), ('overdue', 'просрочена')], default='planned', max_length=100),
        ),
    ]
